### PR TITLE
fix(ts): add `enableInExpoDevelopment` to typings

### PR DESCRIPTION
**Pull request by SimenB**
See https://github.com/expo/sentry-expo/pull/58#discussion_r323226432

### CODE REVIEW

**Comment by nehresma** [comment]
Any chance of this (or something very similar) getting merged and 2.0.1 being released?  Sounds like there are a number of us getting these build errors with 2.0.0.

**Comment by cruzach** [comment]
Hi, sorry I've been away. I'll test this and merge/release tomorrow!

**Comment by nehresma** [comment]
No worries, thanks Charlie!

**Comment by cruzach** [comment]
Thanks for this one @SimenB! 2.0.1 is released 🎉

**Pull request merged**
