### PR TITLE
fix: add peer dependency on `expo`

### PR DESCRIPTION
**Pull request by SimenB**
# Checklist

- [x] I've added an entry to [CHANGELOG.md](https://github.com/expo/sentry-expo/blob/main/CHANGELOG.md#master) if necessary.

# Why

Without this, the following warnings are printed when running `yarn` in this repo

```
warning " > expo-updates@0.14.3" has unmet peer dependency "expo@*".
warning "expo-updates > expo-updates-interface@0.7.0" has unmet peer dependency "expo@*".
```

# How

Just updated `package.json` and ran `yarn`

# Test Plan

🤷

### CODE REVIEW

**Comment by kbrandwijk** [comment]
`expo` is already in the `devDependencies` as well, so this seems to be more of a yarn quirk than anything else.

**Comment by SimenB** [comment]
> `expo` is already in the `devDependencies` as well, so this seems to be more of a yarn quirk than anything else.

It's not - I added it in _this_ PR

**Comment by kbrandwijk** [comment]
> > `expo` is already in the `devDependencies`
> 
> It's not - I added it in _this_ PR

My bad. I'll run some tests and get this in.

**Comment by SimenB** [comment]
Ping @kbrandwijk 🙂

**Comment by kbrandwijk** [comment]
I'll push a release soon.

**Pull request merged**
