### PR TITLE
feat: upgrade sentry client to v7

### PR DESCRIPTION
**Pull request by SimenB**
See https://github.com/getsentry/sentry-react-native/releases/tag/4.0.0

This is a breaking change

### CODE REVIEW

**Comment by mpodreshetnikov** [comment]
Important update. We need it!

**Comment by SimenB** [comment]
@brentvatne PTAL 😀

**Review by LFMAKER — APPROVED** [review]

**Comment by johnsoncwb** [comment]
@brentvatne some idea when we receive this att? are some issues to build in iOS

**Review by johnsoncwb — APPROVED** [review]

**Review by flavio-dias-mm — APPROVED** [review]
@brentvatne PTAL

**Comment by brentvatne** [comment]
hi there! this looks like something we should ship with the upcoming sdk 46. @kbrandwijk is the maintainer of this library now so I have asked him to take a look

**Comment by kbrandwijk** [comment]
Thank you for your contribution. These changes have been rolled into https://github.com/expo/sentry-expo/pull/266.

**Pull request closed without merging**
