### PR TITLE
Bump sentry react native version

### PR DESCRIPTION
**Pull request by cheungt6**
# Checklist

- [X] I've added an entry to [CHANGELOG.md](https://github.com/expo/sentry-expo/blob/main/CHANGELOG.md#master) if necessary.

# Why

Enable the use of captureUserFeedback from the ReactNativeClient.
This was introduced in a later version than currently referenced

Sentry.Native.ReactNativeClient.captureUserFeedback(userFeedback);

# How

Bump the version of the library @sentry/react-native in the package.json

# Test Plan

Call Sentry.Native.ReactNativeClient.captureUserFeedback(userFeedback); and view results in dashboard

### CODE REVIEW

**Comment by cheungt6** [comment]
@kbrandwijk pls review

**Review by kbrandwijk — CHANGES_REQUESTED** [review]
Thank you for your contribution! I've taken a look at the changelogs over on `@sentry/react-native` and from what I can see, a bump to their latest version (4.12.0) looks safe. Could you update your PR to bump directly to 4.12.0 please?

**Comment by cheungt6** [comment]
@kbrandwijk this is done. thanks

**Review by krystofwoldrich — APPROVED** [review]
I will be happy to see the new version of `@sentry/react-native` in `sentry-expo`.

**Comment by cheungt6** [comment]
@kbrandwijk @krystofwoldrich  pls merge

**Comment by krystofwoldrich** [comment]
@cheungt6 @jbagaresgaray I can't merge in this repo. Someone from the [Expo team](https://github.com/expo) can do it.

**Comment by kbrandwijk** [comment]
It seems that this bump causes ts errors.

**Comment by kbrandwijk** [comment]
Superseded by #314

**Pull request closed without merging**
