### PR TITLE
Upgrade to sentry-react-native 5.10.0 and sentry-javascript 7.69.0

### PR DESCRIPTION
**Pull request by krystofwoldrich**
# Checklist

- [x] I've added an entry to [CHANGELOG.md](https://github.com/expo/sentry-expo/blob/main/CHANGELOG.md#master) if necessary.

# Why

Customers having this issue have to manually upgrade the cli at the moment.

- https://github.com/expo/sentry-expo/issues/364

- supersedes https://github.com/expo/sentry-expo/pull/367 and https://github.com/expo/sentry-expo/pull/358

### CODE REVIEW

**Comment by ceafive** [comment]
Can we get this merged?

**Comment by sergey-king** [comment]
> Can we get this merged?

+1

**Comment by szt217** [comment]
+1. Can we get this merged, please? My team can use this update.

**Comment by victoralmeidadev** [comment]
> Can we get this merged?

+1

**Comment by raphaelm-gioa** [comment]
Hi, I see this being ready and not merged, bumping 😊 thanks

**Comment by sergey-king** [comment]
@brentvatne anyone from the sentry team can look at this? We'd love to get this merge

**Comment by rflukes** [comment]
+1, would love to get this merged

**Review by brentvatne — APPROVED** [review]

**Comment by brentvatne** [comment]
please install sentry-expo@7.1.1 to get the version with this patch applied. once you have done so, please report back to verify that everything is working well in your app. if a few folks report back success, i'll go ahead and promote this to the default version for sdk 49

**Comment by SimenB** [comment]
Supersedes #358

**Comment by joeporpeglia** [comment]
@brentvatne after upgrading to `sentry-expo@7.1.1` and `@sentry/react-native@5.10.0` it looks like source maps are uploaded for both ios and android, but stack traces aren't being mapped correctly. When I run `sentry-cli sourcemaps explain` it says `Event exception stacktrace selected frame (0) has incorrect abs_path (valid url is required).` 

Both ios and android builds were done through EAS - I can provide a link to the builds if that's helpful.

**Comment by Arashadmin** [comment]
Hi! I'm a bit confused again :/ 

I'm using sentry-expo@7.1.1 and @sentry/react-native@5.15.1 in order to get rid of this issue [here](https://github.com/getsentry/sentry-react-native/issues/3421#:~:text=Hi%20%40Arashadmin!%20The%20fix%20is%20part%20of%20sentry%2Dreact%2Dnative%205.15.0.%20The%20fix%20on%20the%20iOS%20SDK%20was%20part%20of%20the%20sentry%2Dcocoa%208.17.1%20release%2C%20and%20sentry%2Dreact%2Dnative%205.15.0%20bumped%20the%20dependency%20to%20that%20version.%20%3A)
).

But as I can see here, sentry-expo@7.1.1 is only compatible with @sentry/react-native@5.10.0 ?
Am I correct? 
Do you know when it'll be compatible with  @sentry/react-native@5.15.1 where I can find the fix for my specific issue? 

Thanks for your reply!
Ari

**Comment by krystofwoldrich** [comment]
Hello @Arashadmin ,
`@sentry/react-native` now supports Expo out of the box!

Update to https://github.com/getsentry/sentry-react-native/releases/tag/5.16.0 or newer to get all the new features.

Migration guides available:
- https://github.com/expo/fyi/blob/main/sentry-expo-migration.md
- https://docs.sentry.io/platforms/react-native/migration/sentry-expo/

**Pull request merged**
